### ISSUE TITLE
Maybe wrong solution in generics3.rs

### ISSUE THREAD

**Issue by balroggg** [satu-n/study-rustlings#1]
https://github.com/satu-n/study-rustlings/blob/72d9106dffb1ad5d6b9c31ed9a2cae4f4921048a/exercises/generics/generics3.rs#L22-L25

I think you don't need to create new types(new enum), but only use generic type. Something like this
```
pub struct ReportCard<T> {
    pub grade: T,
```

And thanks to share solution, it helps me in error exercise.

**Comment by s8sato** [comment]
Thank you for your review!
As you said, my answer had no sense to the exercise.
https://github.com/satu-n/study-rustlings/commit/0315745bc232de849d7ddcd95861758a5b7e0922
Do you think this is okay?

**Comment by balroggg** [comment]
LGTM :+1:
